# Generated by Django 2.0.6 on 2018-07-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180719_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_metadata',
            name='associated_skeds',
        ),
        migrations.AddField(
            model_name='schedule_metadata',
            name='associated_forms',
            field=models.ManyToManyField(related_name='schedules', to='core.Schedule_Metadata'),
        ),
    ]
