# Generated by Django 2.0.6 on 2018-08-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180719_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
    ]
