# Generated by Django 2.0.6 on 2018-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_returncntrctrcmpnstn_returnezcmpnstnhghstpdempl_returnezcmpnstnofhghstpdcntrct_returnezfrgnfnnclaccn'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingFiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_year', models.IntegerField(blank=True, null=True)),
                ('return_id', models.CharField(blank=True, max_length=31, null=True)),
                ('filing_type', models.CharField(blank=True, max_length=31, null=True)),
                ('ein', models.CharField(max_length=31)),
                ('tax_period', models.IntegerField(blank=True, null=True)),
                ('sub_date', models.CharField(blank=True, max_length=31, null=True)),
                ('taxpayer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('return_type', models.CharField(blank=True, max_length=7, null=True)),
                ('dln', models.CharField(blank=True, max_length=31, null=True)),
                ('object_id', models.CharField(blank=True, max_length=31, null=True)),
                ('schema_version', models.TextField(blank=True, null=True)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('parse_started', models.IntegerField(blank=True, null=True)),
                ('parse_complete', models.IntegerField(blank=True, null=True)),
                ('process_time', models.DateTimeField(blank=True, null=True)),
                ('is_error', models.IntegerField(blank=True, null=True)),
                ('key_error_count', models.IntegerField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filing_filing',
                'managed': False,
            },
        ),
    ]
