# Generated by Django 2.0.6 on 2018-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filingfiling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_metadata',
            name='irs_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='field_metadata',
            name='line_number',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
