# Generated by Django 2.0.6 on 2018-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180611_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field_metadata',
            name='ordering',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='schedule_part_metadata',
            name='ordering',
            field=models.FloatField(),
        ),
    ]
