# Generated by Django 2.0.6 on 2018-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180814_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ein',
            field=models.CharField(db_index=True, max_length=31, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='taxpayer_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
    ]
