# Generated by Django 2.0.6 on 2018-06-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180611_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='field_metadata',
            name='attribute_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
