# Generated by Django 2.0.6 on 2018-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_field_metadata_attribute_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('ein', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('taxpayer_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'core_organization',
                'managed': False,
            },
        ),
    ]
