# Generated by Django 2.0.6 on 2018-08-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180814_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiscalYear',
            new_name='Fiscal_Year',
        ),
    ]
