# Generated by Django 2.0.6 on 2018-06-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.FloatField()),
                ('name', models.CharField(max_length=255, verbose_name='parent schedule name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schedule_part_metadata',
            name='parent_sked_part',
        ),
        migrations.AlterField(
            model_name='field_metadata',
            name='parent_sked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Schedule_Metadata'),
        ),
        migrations.AlterField(
            model_name='field_metadata',
            name='parent_sked_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Schedule_Part_Metadata'),
        ),
        migrations.AlterField(
            model_name='schedule_part_metadata',
            name='parent_sked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Schedule_Metadata'),
        ),
    ]
