# Generated by Django 2.0.6 on 2018-06-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180620_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_part_metadata',
            name='part_key',
            field=models.CharField(default=0, max_length=255, verbose_name='schedule part key'),
            preserve_default=False,
        ),
    ]
