# Generated by Django 2.0.6 on 2018-06-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_schedule_part_metadata_part_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_metadata',
            name='ordering',
        ),
    ]
