# Generated by Django 2.0.6 on 2018-06-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field_Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_sked', models.CharField(max_length=255)),
                ('parent_sked_part', models.CharField(max_length=255)),
                ('ordering', models.IntegerField()),
                ('in_a_group', models.BooleanField()),
                ('db_table', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=255)),
                ('xpath', models.CharField(max_length=510)),
                ('irs_type', models.CharField(max_length=255)),
                ('db_type', models.CharField(max_length=255)),
                ('line_number', models.IntegerField(max_length=255)),
                ('description', models.TextField()),
                ('versions', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule_Part_Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_sked', models.CharField(max_length=255)),
                ('parent_sked_part', models.CharField(max_length=255)),
                ('ordering', models.IntegerField()),
                ('part_name', models.CharField(max_length=255, verbose_name='verbose schedule part name')),
                ('xml_root', models.CharField(max_length=255)),
                ('is_shell', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
