# Generated by Django 2.0.6 on 2018-06-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efile_export', '0002_auto_20180607_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field_Metadata',
        ),
        migrations.DeleteModel(
            name='Schedule_Part_Metadata',
        ),
    ]
