# Generated by Django 2.0.6 on 2018-06-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_remove_schedule_metadata_ordering'),
        ('efile_export', '0003_auto_20180608_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.EmailField(max_length=254)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('marked_for_deletion', models.BooleanField(default=False)),
                ('fields', models.ManyToManyField(to='core.Field_Metadata')),
                ('orgs', models.ManyToManyField(to='core.Organization')),
            ],
        ),
    ]
